$ErrorActionPreference = "Stop"

Write-Host "Running SkillBridge checks..." -ForegroundColor Cyan

$python = Join-Path $PSScriptRoot "..\.venv\Scripts\python.exe"
if (-not (Test-Path $python)) {
    $python = "python"
}

Write-Host "`n[1/5] Validate documentation files"
$required = @(
    "README.md",
    "docs/PRODUCT_SPEC.md",
    "docs/ARCHITECTURE.md",
    "docs/SOURCE_ADAPTERS.md",
    "docs/DATA_MODEL.md",
    "docs/OPPORTUNITY_SCHEMA.md",
    "docs/MATCHING_DESIGN.md",
    "docs/API_SPEC.md",
    "docs/FOLDER_STRUCTURE.md",
    "docs/USER_RESEARCH_PLAN.md",
    "docs/ROADMAP.md",
    "docs/RUNNING_LOCALLY.md",
    "docs/STREAK.md"
)
foreach ($file in $required) {
    if (-not (Test-Path $file)) {
        throw "Missing required file: $file"
    }
}

# Every document linked from the README must exist, or the entry point lies.
$readme = Get-Content README.md -Raw
$links = [regex]::Matches($readme, '\]\((docs/[^)#]+\.md)\)')
foreach ($link in $links) {
    $target = $link.Groups[1].Value -replace '/', '\'
    if (-not (Test-Path $target)) {
        throw "README links to a missing document: $($link.Groups[1].Value)"
    }
}
Write-Host "README document links verified ($($links.Count) links)."

# The streak report must carry its provenance banner. A hand-written number in
# that file is exactly the failure mode the tracker exists to prevent.
$streak = Get-Content docs/STREAK.md -Raw
if ($streak -notmatch 'Generated by `scripts/streak\.py` from `git log HEAD`') {
    throw "docs/STREAK.md is missing its git provenance banner; regenerate it with scripts/update-streak.ps1"
}
Write-Host "Streak report provenance verified."

Write-Host "`n[2/5] Python tests"
& $python -m unittest discover -s backend/tests -v
if ($LASTEXITCODE -ne 0) { throw "Python tests failed" }

Write-Host "`n[3/5] Streak report matches real git history"
$env:PYTHONIOENCODING = "utf-8"
$stats = & $python scripts/streak.py --repo . --json | ConvertFrom-Json
if ($LASTEXITCODE -ne 0) { throw "Streak tracker could not read git history" }
if ($stats.total_commits -lt 1) { throw "Streak tracker read zero commits; git history looks wrong" }
Write-Host "Streak: $($stats.streak) day(s) current, $($stats.longest) longest, $($stats.total_commits) total commits."

Write-Host "`n[4/5] Python and frontend checks"
& $python -m compileall -q backend/app
if ($LASTEXITCODE -ne 0) { throw "Python compilation failed" }
node --check frontend/app.js
if ($LASTEXITCODE -ne 0) { throw "Frontend syntax check failed" }
node --check frontend/three-scene.js
if ($LASTEXITCODE -ne 0) { throw "3D scene syntax check failed" }
node --test frontend/tests/scene.test.js
if ($LASTEXITCODE -ne 0) { throw "3D scene tests failed" }

Write-Host "`n[5/5] Git whitespace check"
if (Test-Path ".git") {
    git diff --check
    if ($LASTEXITCODE -ne 0) {
        throw "Git whitespace check failed"
    }
} else {
    Write-Host "Git repository not initialized yet; skipped."
}

Write-Host "`nAll checks passed." -ForegroundColor Green
